# Generated by Django 5.2.4 on 2026-01-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='carbohydrate',
            field=models.FloatField(default=0.0, verbose_name='탄수화물(g)'),
        ),
        migrations.AddField(
            model_name='post',
            name='fat',
            field=models.FloatField(default=0.0, verbose_name='지방(g)'),
        ),
        migrations.AddField(
            model_name='post',
            name='kcal',
            field=models.FloatField(default=0.0, verbose_name='칼로리'),
        ),
        migrations.AddField(
            model_name='post',
            name='protein',
            field=models.FloatField(default=0.0, verbose_name='단백질(g)'),
        ),
    ]
