# Generated by Django 6.0 on 2025-12-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=32)),
                ('main_actor', models.CharField(max_length=32)),
                ('genre', models.CharField(max_length=32)),
                ('rating', models.FloatField()),
                ('release_year', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
