# Generated by Django 6.0 on 2025-12-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('action', '액션'), ('romance', '로맨스'), ('comedy', '코미디'), ('sf', 'SF'), ('horror', '공포')], max_length=32),
        ),
    ]
