# Generated by Django 6.0.1 on 2026-01-22 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('image_caption', '이미지 캡셔닝'), ('speech_to_text', '음성→텍스트'), ('audio_genre', '음악 장르 분류'), ('podcast_maker', '팟캐스트 메이커')], max_length=50)),
                ('input_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('result_text', models.TextField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI 사용 내역',
                'verbose_name_plural': 'AI 사용 내역들',
                'ordering': ['-created_at'],
            },
        ),
    ]
